import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Nav from "./components/layouts/Nav";
import Menu from "./components/Menu";
import StateWrapper from "./components/stateful_wrapper/StateWrapper";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  preload: true,
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} scrollbar-none`}>
        <StateWrapper />
        {children}
      </body>
    </html>
  );
}
